### ISSUE TITLE
Mypy -> TypedDict "_ClientErrorResponseTypeDef" has no key "CancellationReasons"  [typeddict-item]

### ISSUE THREAD

**Issue by ArtemSliusarenko** [youtype/botocore-stubs#1]
Why is [_ClientErrorResponseTypeDef](https://github.com/youtype/botocore-stubs/blob/6e980475ca037e3d5219471767bc1c17783c4ee0/botocore-stubs/exceptions.pyi#L23) not include `CancellationReasons`?

**Comment by vemel** [comment]
THank you for the report!

As I see, CI failed to find this inconsistency. I will update the stubs ASAP.

**Comment by vemel** [comment]
Looks like it is specific to `dynamodb` errors only. I will add an optional key.

**Comment by vemel** [comment]
Added. WIll be included in `botocore-stubs 1.29.70` release. Please test it and let me know if it works as it should.

**Comment by ArtemSliusarenko** [comment]
Thank you for the timely response. Will definitely test the release and get back to you.

**Comment by vemel** [comment]
Unfortunately, these inconsistencies cannot be found by CI, because these models only exist in `botocore` schemas, not in Python code. So, please keep reporting if you find any other issues.

**Comment by ArtemSliusarenko** [comment]
This solves our issue. Thanks a lot.
