### ISSUE TITLE
AUR build fails, missing setup.py

### ISSUE THREAD

**Issue by mbpowers** [youtype/botocore-stubs#5]
When updating to the newest version in the [AUR](https://aur.archlinux.org/packages/python-botocore-stubs) the build fails and returns
```
Starting package()... /usr/sbin/python: can't open file '/home/user/.cache/yay/python-botocore-stubs/src/botocore_stubs-1.31.38/setup.py': [Errno 2] No such file or directory
```
It looks like `setup.py` isn't in the source at https://files.pythonhosted.org/packages/1e/95/936de5991cd2f2eede891d1612ccce43d1bbeaf64329d1784357cd8574e6/botocore_stubs-1.31.38.tar.gz.

**Comment by vemel** [comment]
Thank you! I will try to fix it today.

**Comment by vemel** [comment]
Finally, fixed. THank you for waiting :) Please let me know if it works as it should.

**Comment by mbpowers** [comment]
Installs just fine now, thanks!
