### ISSUE TITLE
Incorrect typing for `botocore.auth.AUTH_TYPE_MAPS`

### ISSUE THREAD

**Issue by wRAR** [youtype/botocore-stubs#8]
https://github.com/youtype/botocore-stubs/blob/3dc924f458fc4418eae780293b26090133bba468/botocore-stubs/auth.pyi#L124 is incorrect: the dict values are `Type[BaseSigner]`, not `BaseSigner`.

**Comment by vemel** [comment]
Thank you! I changed typing of `AUTH_TYPE_MAPS` and `CRT_AUTH_TYPE_MAPS` to `Dict[str, Type[BaseSigner]]`.

I also released `botocore-stubs 1.32.3.post1` with the fix included. Please update and let me know if it works as it should.

**Comment by wRAR** [comment]
Thanks! It works correctly now.
